#!/usr/bin/env -S uv run --script
# /// script
# requires-python = "==3.13"
# dependencies = [
#   "pydantic",
# ]
# ///

from pydantic import BaseModel
from datetime import date as Date
from pathlib import Path
import json
from argparse import ArgumentParser

STATE_PATH = Path("~/.checkin_state.json").expanduser()


class State(BaseModel):
    checked_in: Date | None = None
    checked_out: Date | None = None

    @staticmethod
    def load() -> "State":
        if not STATE_PATH.is_file():
            return State(people=[])

        with STATE_PATH.open("r") as f:
            return State(**json.load(f))

    def store(self):
        with STATE_PATH.open("w") as f:
            f.write(self.model_dump_json(indent=4))


parser = ArgumentParser()
parser.add_argument("--check", action="store_true")

args = parser.parse_args()


state = State.load()

# Only run check-in on weekdays
if args.check or Date.today().weekday() >= 5:
    if state.checked_in != Date.today():
        print("You haven't checked in for today. Please do so by running `ci`")
    exit()

if state.checked_in == Date.today():
    print("You are already checked in")
    exit()


if state.checked_in is not None and state.checked_in != state.checked_out:
    print("You haven't checked out last time. Please do so first by running `co`")
    exit()


CHECKLIST = [
    "Wrote plan for today in BuJo",
    "Filled status update document",
]


try:
    for item in CHECKLIST:
        while input(item + ": ").strip().lower() != "yes":
            print("Please type `yes` to continue")

except KeyboardInterrupt:
    exit()

state.checked_in = Date.today()
state.store()
