#!/usr/bin/env python

from pathlib import Path
import sys
sys.path.append(str(Path(__file__).resolve().parents[1]))
import credentials

import argparse

parser = argparse.ArgumentParser("Get local credentials")
parser.add_argument("key", type=str)
args = parser.parse_args()

if not hasattr(credentials, args.key):
    print(f"Credential '{args.key}' is not set", file=sys.stderr)
else:
    print(getattr(credentials, args.key))
