#!/bin/bash

# param validation
if [[ ! $(git log -n 1 "$@" | head -n 1) ]] ;then
  exit
fi

# filter by file string
# param existed, git log for file if existed
if [ -n "$*" ] && [ -f "$*" ]; then
  filter="-- $*"
fi

# git command
gitlog=(
  git log
  --graph --color=always
  --abbrev=7
  --format='%C(auto)%h %an %C(blue)%s %C(yellow)%cr'
  "$@"
)

# fzf command
fzf=(
  fzf
  --ansi --no-sort --reverse --tiebreak=index
  --preview "f() { set -- \$(echo -- \$@ | grep -o '[a-f0-9]\{7\}'); [ \$# -eq 0 ] || git show --color=always \$1 $filter; }; f {}"
 --preview-window=right:60%
)

"${gitlog[@]}" | "${fzf[@]}" | grep -o '[a-f0-9]\{7\}' | xargs -I{} git rev-parse {}
