#!/usr/bin/env python3

from os import environ as env
from pathlib import Path

for folder in env.get("PROJECT_FOLDERS", "").split(":"):
    for p in (Path.home() / folder).iterdir():
        if p.is_dir():
            print(p.resolve())
