#!/usr/bin/env python3

from os import environ as env
from pathlib import Path

for folder in env.get("PROJECT_FOLDERS", "").split(":"):
    folder = (Path.home() / folder).resolve()
    if not folder.is_dir():
        continue
    for p in folder.iterdir():
        if p.is_dir():
            print(p)
